#!/bin/bash

echo "========================================"
echo "Step 9: Monitoring and Troubleshooting"
echo "========================================"

echo ""
echo "Useful monitoring commands:"
echo ""
echo "1. View Nomad logs:"
echo "   journalctl -u nomad -f"
echo ""
echo "2. Check node status:"
echo "   nomad node status"
echo ""
echo "3. Check server members:"
echo "   nomad server members"
echo ""
echo "4. View all jobs:"
echo "   nomad job status"
echo ""
echo "5. View specific job:"
echo "   nomad job status firecracker-example"
echo ""
echo "6. View allocations:"
echo "   nomad alloc status <allocation-id>"
echo ""
echo "7. Check driver health:"
echo "   nomad node status -self | grep firecracker"
echo ""
echo "8. View Nomad UI (if enabled):"
echo "   http://localhost:4646"
echo ""
echo "9. Validate job file:"
echo "   nomad job validate /opt/firecracker/firecracker-job.nomad"
echo ""
echo "10. Run job:"
echo "    nomad job run /opt/firecracker/firecracker-job.nomad"
echo ""
echo "11. Stop job:"
echo "    nomad job stop firecracker-example"
echo ""
echo "12. Check system resources:"
echo "    nomad node status -verbose"
echo ""
